channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cadquery=master
  - pip
  - pip:
    - gmsh==4.9.5
    - ipywidgets==7.7.0
    - meshio==5.3.4
    - pmef==0.5.0
    - pythreejs==2.3.0
    - pyvista==0.34.1
    - scipy==1.8.0
