channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cadquery=master
  - pyvista
  - pip
  - pip:
    - gmsh
    - ipywidgets
    - meshio
    - pmef
    - pythreejs
    - scipy
