channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - pip=21.0
  - cadquery=master
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - streamlit
  - pip:
    - gmsh
    - pmef
    - pyvista --install-option="--no-deps"
    - meshio
    - pythreejs
    - ipygany
