channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - cadquery=2
  - pyvista
  - pip=22.0.4
  - gmsh
  - ipywidgets
  - meshio
  - pythreejs
  - scipy
  - pip:
    - pmef
    - numpy==1.22.1
